import assert from "node:assert/strict";
import crypto from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {verifyElevenLabsSignature,mayBypassElevenLabsSignature} from "../../lib/voice/events/elevenlabs-signature-verifier";
import {ELEVENLABS_MAX_TRANSCRIPT_TURNS,ELEVENLABS_MAX_TURN_CHARS,normalizeElevenLabsWebhook} from "../../lib/voice/events/elevenlabs-event-validator";

const read=(path:string)=>readFileSync(resolve(process.cwd(),path),"utf8");
const now=1_800_000_000_000,timestamp=String(Math.floor(now/1000)),secret="test-only-webhook-secret";
const payload=JSON.stringify({type:"post_call_transcription",event_timestamp:Number(timestamp),data:{conversation_id:"conv_test",sip_call_id:"call_test",agent_id:"agent_test",status:"done",transcript:[{role:"agent",message:"Hello"},{role:"user",message:"I need concise follow-up"}]}});
const signature=crypto.createHmac("sha256",secret).update(`${timestamp}.${payload}`).digest("hex");
assert(verifyElevenLabsSignature(payload,`t=${timestamp},v0=${signature}`,secret,now));
assert(!verifyElevenLabsSignature(payload,"",secret,now));
assert(!verifyElevenLabsSignature(payload,"malformed",secret,now));
assert(!verifyElevenLabsSignature(payload+" ",`t=${timestamp},v0=${signature}`,secret,now));
const old=String(Number(timestamp)-1801),oldSig=crypto.createHmac("sha256",secret).update(`${old}.${payload}`).digest("hex");
assert(!verifyElevenLabsSignature(payload,`t=${old},v0=${oldSig}`,secret,now));
const originalNodeEnv=process.env.NODE_ENV,originalBypass=process.env.ELEVENLABS_WEBHOOK_TEST_BYPASS;
Object.assign(process.env,{NODE_ENV:"production",ELEVENLABS_WEBHOOK_TEST_BYPASS:"true"});assert.equal(mayBypassElevenLabsSignature(),false);
Object.assign(process.env,{NODE_ENV:"test",ELEVENLABS_WEBHOOK_TEST_BYPASS:"true"});assert.equal(mayBypassElevenLabsSignature(),true);
Object.assign(process.env,{NODE_ENV:originalNodeEnv,ELEVENLABS_WEBHOOK_TEST_BYPASS:originalBypass});

const normalized=normalizeElevenLabsWebhook(JSON.parse(payload));assert(normalized&&normalized.outcome==="completed"&&normalized.providerCallId==="call_test");
assert.equal(normalizeElevenLabsWebhook({type:"unsupported",event_timestamp:1,data:{conversation_id:"x"}}),null);
assert.equal(normalizeElevenLabsWebhook({type:"post_call_transcription",event_timestamp:1,data:{conversation_id:"x",agent_id:"a",status:"done",transcript:[{role:"system",message:"unsafe"}]}}),null);
assert.equal(normalizeElevenLabsWebhook({type:"post_call_transcription",event_timestamp:1,data:{conversation_id:"x",agent_id:"a",status:"done",transcript:[{role:"user",message:"x".repeat(ELEVENLABS_MAX_TURN_CHARS+1)}]}}),null);
assert.equal(normalizeElevenLabsWebhook({type:"post_call_transcription",event_timestamp:1,data:{conversation_id:"x",agent_id:"a",status:"done",transcript:Array.from({length:ELEVENLABS_MAX_TRANSCRIPT_TURNS+1},()=>({role:"user",message:"x"}))}}),null);
assert.equal(normalizeElevenLabsWebhook({type:"post_call_transcription",event_timestamp:1,data:{agent_id:"a",status:"done",transcript:[]}}),null);
for(const [type,outcome] of [["call_failed","failed"],["call_unanswered","unanswered"],["call_rejected","rejected"]] as const){assert.equal(normalizeElevenLabsWebhook({type,event_timestamp:1,data:{conversation_id:"x"}})?.outcome,outcome);}
assert.equal(normalizeElevenLabsWebhook({type:"post_call_transcription",event_timestamp:1,data:{conversation_id:"x",agent_id:"a",status:"done",transcript:[]}})?.outcome,"completed_without_transcript");

type ReceiptModel={attempt:number;state:"processing"|"failed"|"completed"};
const finish=(receipt:ReceiptModel,attempt:number,succeeded:boolean|null)=>{
  if(succeeded===null)throw new Error("invalid webhook finish");
  if(receipt.attempt!==attempt||receipt.state!=="processing")return "stale_attempt";
  receipt.state=succeeded?"completed":"failed";
  return receipt.state;
};
const receipt:ReceiptModel={attempt:1,state:"processing"};
receipt.attempt=2;
assert.equal(finish(receipt,1,true),"stale_attempt");
assert.equal(receipt.state,"processing");
assert.equal(finish(receipt,1,false),"stale_attempt");
assert.equal(receipt.state,"processing");
assert.equal(finish(receipt,2,true),"completed");
assert.equal(finish(receipt,2,false),"stale_attempt");
assert.throws(()=>finish({attempt:1,state:"processing"},1,null),/invalid webhook finish/);

const route=read("app/api/webhooks/elevenlabs/route.ts"),processor=read("lib/voice/events/elevenlabs-event-processor.ts"),migration=read("supabase/migrations/20260717180000_public_experience_completion.sql"),dispatchMigration=read("supabase/migrations/20260717120000_public_experience_dispatch_integrity.sql"),page=read("app/experience/page.tsx"),reflection=read("app/api/experience/session/reflection/route.ts"),preflight=read("docs/database/preflight/public_experience_completion_preflight.sql"),verification=read("docs/database/verification/public_experience_completion_verification.sql"),rollback=read("docs/database/rollbacks/public_experience_completion_rollback.sql");
assert(route.indexOf("verifyElevenLabsSignature")<route.indexOf("JSON.parse"));
assert(route.includes("if(!secret)")&&route.includes("Webhook authentication is unavailable"));
assert(!route.includes("console."));
for(const rpc of ["zeya_begin_voice_webhook_receipt","zeya_finish_voice_webhook_receipt","zeya_repair_public_experience_dispatch","zeya_record_public_experience_call_failure"])assert(processor.includes(rpc)&&migration.includes(`CREATE FUNCTION public.${rpc}`));
assert(migration.includes("UNIQUE(provider,event_key)")&&migration.includes("ON CONFLICT(provider,event_key) DO NOTHING"));
assert(migration.includes("inserted=0")&&migration.includes("processing_state='failed'"));
assert(migration.includes("interval '15 minutes'")&&migration.includes("attempt_count=attempt_count+1"));
assert(migration.includes("RETURNS JSONB")&&migration.includes("'attempt',r.attempt_count"));
assert(migration.includes("p_expected_attempt INTEGER")&&migration.includes("r.attempt_count IS DISTINCT FROM p_expected_attempt"));
assert(migration.includes("processing_state='processing' AND attempt_count=p_expected_attempt"));
assert(migration.includes("p_succeeded IS NULL")&&migration.includes("RETURN 'stale_attempt'"));
assert(migration.includes("r.event_type IS DISTINCT FROM p_event_type"));
for(const parameter of ["p_veya_voice_context_id IS NULL","p_provider_conversation_id IS NULL","p_provider_call_id IS NULL"])assert(migration.includes(parameter));
assert(migration.includes("s.provider_conversation_id IS DISTINCT FROM p_provider_conversation_id"));
assert(migration.includes("s.provider_call_id IS DISTINCT FROM p_provider_call_id"));
assert(migration.includes("'call_requested','call_correlation_pending','dispatch_resolution_pending'"));
assert(migration.includes("cardinality(matching_ids) IS DISTINCT FROM 1"));
assert(migration.includes("lineage_created_at>s.expires_at")&&migration.includes("l.created_at<=s.expires_at"));
assert(migration.includes("IF s.state='expired' THEN")&&migration.includes("RETURN 'expired';"));
assert(dispatchMigration.includes("v.expires_at<=now()"));
assert(processor.includes('p_outcome:"completion_processing_failed"'));
assert(processor.includes("voice_representation_lineage")&&processor.includes("canonical_version_id"));
assert(processor.includes("receiptAttempt=acquisition.attempt")&&processor.includes("p_expected_attempt:receiptAttempt"));
assert(processor.indexOf("zeya_repair_public_experience_dispatch")<processor.indexOf("zeya_record_public_experience_call_failure"));
assert(processor.includes('transcriptTrustLevel:"provider_attested"')&&processor.includes("authorized" )===false);
assert(migration.includes("o.provider_attested=true")&&migration.includes("o.transcript_status='finalized'"));
for(const identity of ["o.business_id=s.business_id","o.business_representation_id=s.business_representation_id","o.canonical_version_id=s.canonical_version_id","l.mission_id=s.dispatch_id"])assert(migration.includes(identity));
assert(migration.includes("call_completed_without_transcript")&&migration.includes("call_unanswered")&&migration.includes("call_rejected"));
assert(page.includes('/api/experience/session/status')&&page.includes('window.setTimeout(poll,3000)'));
assert(page.includes('if(stopped||inFlight)return')&&page.includes('return()=>{stopped=true'));
assert(page.includes("new AbortController()")&&page.includes("controller.abort()"));
assert(!page.includes("My Call Is Complete")&&!page.includes("handleCallComplete"));
assert(reflection.includes('session.state!=="reflection_ready"')&&reflection.includes('provider_attested'));
assert(!reflection.includes("canonical_version_id")&&!reflection.includes("provider_call_id")&&!reflection.includes("provider_conversation_id"));
assert(reflection.includes("reviewed before becoming part of the business Representation"));
assert(reflection.includes("[contact detail]")&&reflection.includes("[link]"));
for(const required of ["phase_4b2_session_columns_exact","phase_4b2_state_constraint_exact","phase_4b2_rpcs_exact_and_secure","phase_4b2_table_security_exact","phase_4b2_mutation_trigger_exact","phase_4b2_trigger_function_exact","phase_4b3_no_object_collisions","no_active_dispatch_rows","no_pending_correlation_rows","historical_rows_compatible","controlled_purge_compatible"])assert(preflight.includes(required));
for(const required of ["receipt_columns_exact","receipt_defaults_exact","receipt_keys_exact","receipt_checks_exact","receipt_index_exact","receipt_security_exact","receipt_trigger_exact","receipt_trigger_function_exact","state_constraint_exact","completion_rpcs_exact_and_secure","attempt_fencing_and_identity_exact",'search_path=""',"aclexplode","named_overload_count"])assert(verification.includes(required));
for(const state of ["call_active","call_completed_without_transcript","call_correlation_pending","call_dispatched","call_failed","call_rejected","call_requested","call_unanswered","completion_processing_failed","dispatch_resolution_pending","expired","failed","reflection_ready","zeya_active","zeya_finalized"])assert(verification.includes(`('${state}')`));
const phase4b3States=verification.slice(verification.indexOf("expected_states(state)"),verification.indexOf("state_constraint AS"));
assert.equal((phase4b3States.match(/\('[a-z_]+ '\)/g)??[]).length,0);
assert.equal((phase4b3States.match(/\('[a-z_]+'\)/g)??[]).length,15);
assert(verification.includes("(SELECT count(*) FROM named_rpcs)=5"));
assert(verification.includes("x.grantee NOT IN(a.proowner,(SELECT oid FROM pg_catalog.pg_roles WHERE rolname='service_role'))"));
assert(rollback.includes("Rollback refused")&&rollback.includes("BEGIN;")&&rollback.includes("COMMIT;")&&!rollback.includes("CASCADE"));
assert(rollback.includes("voice_provider_webhook_receipts")&&rollback.includes("veya_conversation_output_id IS NOT NULL")&&rollback.includes("OWNER TO postgres"));
for(const diagnostic of ["test-complete","test-mapping","test-signature","status"]){
  const source=read(`app/api/webhooks/elevenlabs/${diagnostic}/route.ts`);
  assert(source.includes('process.env.NODE_ENV !== "test"')&&source.includes('process.env.PUBLIC_EXPERIENCE_TEST_MODE !== "true"'));
}
console.log("Public Experience provider completion contract — PASS");
