import { createClient } from '@supabase/supabase-js';
import { loadEnvConfig } from '@next/env';
import { startTestServer } from './representation-state-test-server';
import { FixtureRegistry } from './representation-state-test-fixtures';
import { cleanupFixtures } from './representation-state-test-cleanup';
import { jsonRequest } from './representation-state-test-client';

type ContextBody={success:boolean;error?:string;data?:{businessRepresentationId:string;elementCount:number;elements:Array<{elementId:string;elementKey:string;currentValue:{value:string};claimEligibility:string}>}};
const assert=(value:unknown,message:string):void=>{if(!value)throw new Error(`Test D: ${message}`)};
const expectedValues:Record<string,string>={approved_key:'approved value',provisional_key:'provisional value',internal_key:'internal value',disputed_key:'disputed value',prohibited_key:'prohibited value',expired_key:'expired value'};

async function main():Promise<void>{
  loadEnvConfig(process.cwd());const server=await startTestServer(),registry=new FixtureRegistry(),env=process.env;
  const admin=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.SUPABASE_SERVICE_ROLE_KEY!);let cleanup;
  try{
    async function user(label:string){const email=`representation-d-${label}-${registry.runId}@zeya.test`,password=`T-${crypto.randomUUID()}!`,created=await admin.auth.admin.createUser({email,password,email_confirm:true});if(created.error)throw created.error;registry.registerAuthUser(created.data.user.id,email);const auth=createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!),signed=await auth.auth.signInWithPassword({email,password});if(signed.error||!signed.data.session)throw signed.error??new Error('Authentication failed');return{id:created.data.user.id,token:signed.data.session.access_token,client:createClient(env.NEXT_PUBLIC_SUPABASE_URL!,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,{global:{headers:{Authorization:`Bearer ${signed.data.session.access_token}`}}})}}
    const owner=await user('owner'),foreign=await user('foreign');
    const business=await owner.client.from('businesses').insert({business_name:`Test D ${registry.runId}`,user_id:owner.id}).select().single();if(business.error)throw business.error;registry.registerBusiness(business.data.id,owner.id);
    const initial=await jsonRequest<{data:{businessRepresentationId:string;evidenceId:string;observationId:string;proposalId:string}}>(server.baseUrl,'/api/representation/evidence',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${owner.token}`},body:JSON.stringify({businessId:business.data.id,statement:'agent context filtering fixture'})});assert(initial.status===201,'initialization');const rep=initial.body.data.businessRepresentationId;registry.registerBusinessRepresentation(rep,business.data.id);registry.registerEvidence(initial.body.data.evidenceId);registry.registerObservation(initial.body.data.observationId);registry.registerProposal(initial.body.data.proposalId);
    const canonical=await jsonRequest<{data:{versionId:string;confidenceAssessmentId:string}}>(server.baseUrl,'/api/representation/versions',{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${owner.token}`},body:JSON.stringify({businessRepresentationId:rep,proposalId:initial.body.data.proposalId,elementValues:Object.fromEntries(Object.entries(expectedValues).map(([key,value])=>[key,{value}])),confidenceScore:85})});assert(canonical.status===201,'canonical content');registry.registerVersion(canonical.body.data.versionId);registry.registerConfidenceAssessment(canonical.body.data.confidenceAssessmentId);
    const domain=await owner.client.from('representation_domains').select('id').eq('business_representation_id',rep).eq('domain_name','customer').single();if(domain.error)throw domain.error;registry.registerDomain(domain.data.id);
    const states=[['approved_key','approved_for_external_use',false],['provisional_key','provisional',false],['internal_key','internal_only',false],['disputed_key','disputed',true],['prohibited_key','prohibited',false],['expired_key','expired',false]] as const;
    const elements=await owner.client.from('representation_elements').insert(states.map(([element_key,claim_eligibility,is_disputed])=>({business_representation_id:rep,representation_domain_id:domain.data.id,element_key,element_type:'fact',current_value_version_id:canonical.body.data.versionId,is_disputed,claim_eligibility,field_sensitivity:'operational'}))).select();if(elements.error)throw elements.error;elements.data.forEach(row=>registry.registerElement(row.id));assert(elements.data.every(row=>row.current_value_version_id===canonical.body.data.versionId),'all pointers and content');
    const context=(token:string,suffix='')=>jsonRequest<ContextBody>(server.baseUrl,`/api/representation/agent-context?businessRepresentationId=${rep}${suffix}`,{headers:{Authorization:`Bearer ${token}`}});
    const normal=await context(owner.token),provisional=await context(owner.token,'&includeProvisional=true');assert(normal.status===200&&provisional.status===200,'context status');
    const keys=(body:ContextBody)=>[...(body.data?.elements.map(x=>x.elementKey)??[])].sort();assert(JSON.stringify(keys(normal.body))===JSON.stringify(['approved_key']),'default exact keys');assert(JSON.stringify(keys(provisional.body))===JSON.stringify(['approved_key','provisional_key']),'provisional exact keys');
    assert(normal.body.data?.elements[0].currentValue.value==='approved value','approved value');const provisionalRow=provisional.body.data?.elements.find(x=>x.elementKey==='provisional_key');assert(provisionalRow?.currentValue.value==='provisional value','provisional value');
    const serialized=JSON.stringify(provisional.body);for(const hidden of ['internal_key','disputed_key','prohibited_key','expired_key','internal value','disputed value','prohibited value','expired value'])assert(!serialized.includes(hidden),`no leakage ${hidden}`);assert(!serialized.includes('raw_statement')&&!serialized.includes('evidence_id')&&!serialized.includes('user_id'),'structured context only');
    const foreignContext=await context(foreign.token);assert(foreignContext.status===404&&JSON.stringify(foreignContext.body)===JSON.stringify({success:false,error:'Representation not found'}),'tenant restriction');
    const invalid=await context(owner.token,'&includeProvisional=invalid');assert(invalid.status===200&&JSON.stringify(keys(invalid.body))===JSON.stringify(['approved_key']),'invalid parameter is strict false');
    console.log('Representation State Integration\n\nInfrastructure — PASS\nTest D — PASS\nApproved context — PASS\nDefault filtering — PASS\nProvisional inclusion — PASS\nInternal exclusion — PASS\nDisputed exclusion — PASS\nProhibited exclusion — PASS\nExpired exclusion — PASS\nTenant restriction — PASS');
  }finally{cleanup=await cleanupFixtures(admin,registry);console.log(`Representation cleanup — ${cleanup.success?'PASS':'FAIL'}\nBusiness cleanup — ${cleanup.success?'PASS':'FAIL'}\nAuth cleanup — ${cleanup.success?'PASS':'FAIL'}`);await server.stop();console.log('Server cleanup — PASS')}
  if(!cleanup?.success)throw new Error(cleanup.failures.join(', '));
}
const keepAlive=setInterval(()=>{},1000);main().catch(error=>{console.error(error instanceof Error?error.message:'Test D failed');process.exitCode=1}).finally(()=>clearInterval(keepAlive));
