import { execFileSync } from "node:child_process";
import { loadEnvConfig } from "@next/env";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { FixtureRegistry } from "./representation-state-test-fixtures";
import { cleanupFixtures } from "./representation-state-test-cleanup";
import { jsonRequest } from "./representation-state-test-client";
import { startTestServer } from "./representation-state-test-server";

type User={id:string;token:string;client:SupabaseClient};
type Tenant={user:User;businessId:string;representationId:string;versionId:string;versionNumber:number;targetElementId:string;otherElementId:string};
type Canonical={reviewDecisionId:string;promotionId:string;proposalId:string;approvalDecisionId:string;baselineCanonicalVersionId:string;canonicalVersionId:string;canonicalVersionNumber:number;confidenceAssessmentId:string;canonicalizationId:string;idempotent:boolean};
function assert(v:unknown,m:string):asserts v{if(!v)throw new Error(`Voice Candidate Canonicalization Deployed: ${m}`)}

async function main(){
 loadEnvConfig(process.cwd()); const url=process.env.NEXT_PUBLIC_SUPABASE_URL,publishable=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,key=process.env.SUPABASE_SERVICE_ROLE_KEY;
 assert(url&&publishable&&key,"required environment unavailable");
 const testDbUrl=process.env.ZEYA_TEST_DB_URL,testProjectRef=process.env.ZEYA_TEST_PROJECT_REF;
 assert(testDbUrl&&testProjectRef,"explicit preview database target unavailable");
 assert(testProjectRef!=="eqdhftogzzlkpjebgbue"&&url.includes(testProjectRef),"schema mutation target is not an isolated preview");
 const server=await startTestServer(),registry=new FixtureRegistry(),service=createClient(url,key,{auth:{persistSession:false}}),anon=createClient(url,publishable,{auth:{persistSession:false}});
 let rollbackConstraint=false,cleanup:Awaited<ReturnType<typeof cleanupFixtures>>|undefined,phase="setup";
 const sql=(statement:string)=>execFileSync("npx",["supabase","db","query","--db-url",testDbUrl,statement],{cwd:process.cwd(),stdio:"pipe",encoding:"utf8"});
 async function user(label:string){const email=`canonical-${label}-${registry.runId}@zeya.test`,password=`T-${crypto.randomUUID()}!`,created=await service.auth.admin.createUser({email,password,email_confirm:true});if(created.error)throw created.error;registry.registerAuthUser(created.data.user.id,email);const publicClient=createClient(url!,publishable!,{auth:{persistSession:false}}),signed=await publicClient.auth.signInWithPassword({email,password});if(signed.error||!signed.data.session)throw signed.error;return{id:created.data.user.id,token:signed.data.session!.access_token,client:createClient(url!,publishable!,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${signed.data.session!.access_token}`}}})}}
 async function tenant(label:string):Promise<Tenant>{const u=await user(label),business=await u.client.from("businesses").insert({business_name:`Canonical ${label} ${registry.runId}`,user_id:u.id}).select().single();if(business.error)throw business.error;registry.registerBusiness(business.data.id,u.id);const evidence=await jsonRequest<any>(server.baseUrl,"/api/representation/evidence",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${u.token}`},body:JSON.stringify({businessId:business.data.id,statement:`baseline ${label}`})});assert(evidence.status===201,`${label} baseline evidence`);const rep=evidence.body.data.businessRepresentationId;registry.registerBusinessRepresentation(rep,business.data.id);registry.registerEvidence(evidence.body.data.evidenceId);registry.registerObservation(evidence.body.data.observationId);registry.registerProposal(evidence.body.data.proposalId);const version=await jsonRequest<any>(server.baseUrl,"/api/representation/versions",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${u.token}`},body:JSON.stringify({businessRepresentationId:rep,proposalId:evidence.body.data.proposalId,elementValues:{voice_target:{value:`baseline ${label}`}},confidenceScore:70})});assert(version.status===201,`${label} baseline version`);registry.registerVersion(version.body.data.versionId);registry.registerConfidenceAssessment(version.body.data.confidenceAssessmentId);const vr=await service.from("representation_versions").select("version_number").eq("id",version.body.data.versionId).single();if(vr.error)throw vr.error;const domain=await u.client.from("representation_domains").select("id").eq("business_representation_id",rep).limit(1).single();if(domain.error)throw domain.error;registry.registerDomain(domain.data.id);const elements=await u.client.from("representation_elements").insert([{business_representation_id:rep,representation_domain_id:domain.data.id,element_key:"voice_target",element_type:"fact",current_value_version_id:version.body.data.versionId,field_sensitivity:"strategic_positioning"},{business_representation_id:rep,representation_domain_id:domain.data.id,element_key:"voice_other",element_type:"fact",current_value_version_id:version.body.data.versionId,field_sensitivity:"operational"}]).select();if(elements.error)throw elements.error;elements.data.forEach(x=>registry.registerElement(x.id));return{user:u,businessId:business.data.id,representationId:rep,versionId:version.body.data.versionId,versionNumber:Number(vr.data.version_number),targetElementId:elements.data[0].id,otherElementId:elements.data[1].id}}
 async function candidate(t:Tenant,label:string){const context=crypto.randomUUID(),conversation=`canonical-${label}-${registry.runId}`;const lineage=await service.rpc("zeya_create_voice_representation_lineage",{p_voice_context_id:context,p_worker_brief_id:`brief-${label}`,p_mission_id:`mission-${label}`,p_conversation_id:conversation,p_tenant_user_id:t.user.id,p_business_id:t.businessId,p_business_representation_id:t.representationId,p_canonical_version_id:t.versionId,p_context_generated_at:new Date().toISOString(),p_authorized_element_keys:["voice_target"],p_provisional_mode:false,p_agent_id:"veya-caller",p_agent_type:"CALLER",p_agent_role:"test",p_context_schema_version:"1.0",p_prompt_assembly_version:"1.0"});if(lineage.error)throw lineage.error;registry.registerVoiceLineage(context,t.representationId);const output=await service.rpc("zeya_capture_voice_conversation_output",{p_voice_context_id:context,p_conversation_id:conversation,p_provider_call_id:null,p_provider:"elevenlabs",p_channel:"veya_outbound",p_capture_source:"provider_callback",p_transcript_trust_level:"provider_attested",p_provider_attested:true,p_submitted_by:null,p_started_at:new Date().toISOString(),p_completed_at:new Date().toISOString(),p_transcript:[{role:"customer",text:`confirmed ${label}`}],p_transcript_status:"finalized",p_transcript_schema_version:"1.0",p_conversation_status:"done",p_completion_reason:"provider_completed",p_extraction_schema_version:"1.0",p_safe_metadata:{test:true}});if(output.error)throw output.error;registry.registerVoiceOutput(output.data,t.representationId);const stored=await service.rpc("zeya_store_voice_conversation_candidates",{p_conversation_output_id:output.data,p_extraction_schema_version:"1.0",p_candidates:[{candidateType:"possible_representation_gap",content:{summary:`confirmed ${label}`},speakerRole:"customer",statementKind:"assertion",sourceReference:{turnIndexes:[0]},relevantElementKeys:["voice_target"],confidence:.86,rationale:"provider-attested source"}]});if(stored.error)throw stored.error;const row=await service.from("voice_conversation_candidates").select("*").eq("conversation_output_id",output.data).single();if(row.error)throw row.error;registry.registerVoiceCandidate(row.data.id,t.representationId);return row.data}
 const args=(t:Tenant,c:any,request:string,statement:string,actor=t.user.id)=>({p_actor_user_id:actor,p_candidate_id:c.id,p_request_key:request,p_confirmed_content:{statement,elementKey:"voice_target"},p_reason:"Founder confirmed",p_related_element_id:t.targetElementId,p_element_values:{voice_target:{value:statement}},p_overall_confidence_score:86,p_approval_reason:"Founder approved"});
 const track=(t:Tenant,r:Canonical)=>{registry.registerConversationReview(r.reviewDecisionId,t.representationId);registry.registerConversationPromotion(r.promotionId,t.representationId);registry.registerProposal(r.proposalId);registry.registerApproval(r.approvalDecisionId);registry.registerVersion(r.canonicalVersionId);registry.registerConfidenceAssessment(r.confidenceAssessmentId);registry.registerConversationCanonicalization(r.canonicalizationId,t.representationId)};
 try{
  phase="fixtures";const owner=await tenant("owner"),foreign=await tenant("foreign"),c=await candidate(owner,"happy"),request=crypto.randomUUID(),statement="Founder-confirmed canonical voice";
  phase="authorization";assert((await owner.user.client.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement))).error,"authenticated owner blocked");assert((await foreign.user.client.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement))).error,"foreign authenticated blocked");assert((await anon.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement))).error,"anon blocked");assert((await service.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement,foreign.user.id))).error,"foreign actor blocked");
  phase="happy path";const call=await service.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement));if(call.error)throw call.error;const result=call.data as Canonical;assert(!result.idempotent,"first call non-idempotent");track(owner,result);
  const [review,promotion,proposal,approval,version,rep,elements,audit,confidence,provenance,pe,po,pel]=await Promise.all([service.from("conversation_candidate_review_decisions").select("*").eq("id",result.reviewDecisionId).single(),service.from("conversation_candidate_promotions").select("*").eq("id",result.promotionId).single(),service.from("representation_proposals").select("*").eq("id",result.proposalId).single(),service.from("approval_decisions").select("*").eq("id",result.approvalDecisionId).single(),service.from("representation_versions").select("*").eq("id",result.canonicalVersionId).single(),service.from("business_representations").select("current_version_id").eq("id",owner.representationId).single(),service.from("representation_elements").select("id,current_value_version_id").in("id",[owner.targetElementId,owner.otherElementId]),service.from("audit_events").select("*").eq("version_id",result.canonicalVersionId).eq("event_type","version_created"),service.from("confidence_assessments").select("*").eq("id",result.confidenceAssessmentId).single(),service.from("conversation_candidate_canonicalizations").select("*").eq("id",result.canonicalizationId).single(),service.from("proposal_evidence").select("*").eq("proposal_id",result.proposalId),service.from("proposal_observations").select("*").eq("proposal_id",result.proposalId),service.from("proposal_elements").select("*").eq("proposal_id",result.proposalId)]);
  assert(!review.error&&!promotion.error&&!proposal.error&&!approval.error&&!version.error&&!rep.error&&!confidence.error&&!provenance.error,"terminal rows exist");assert(proposal.data.status==="approved"&&approval.data.decision==="approved"&&approval.data.approver_user_id===owner.user.id,"approval lineage");assert(version.data.version_number===owner.versionNumber+1&&version.data.previous_version_id===owner.versionId&&version.data.source_proposal_id===result.proposalId&&version.data.source_approval_id===result.approvalDecisionId,"Version lineage");assert(rep.data.current_version_id===result.canonicalVersionId,"Representation pointer");assert(elements.data?.find(x=>x.id===owner.targetElementId)?.current_value_version_id===result.canonicalVersionId&&elements.data?.find(x=>x.id===owner.otherElementId)?.current_value_version_id===owner.versionId,"Element pointers");assert(audit.data?.length===1&&confidence.data.business_representation_id===owner.representationId&&confidence.data.representation_version_id===result.canonicalVersionId&&confidence.data.confidence_band==="very_high","Audit and Confidence");assert(pe.data?.length===1&&po.data?.length===1&&pel.data?.length===1,"Proposal joins");assert(provenance.data.baseline_canonical_version_id===owner.versionId&&provenance.data.canonical_version_id===result.canonicalVersionId&&provenance.data.candidate_id===c.id&&provenance.data.actor_user_id===owner.user.id,"complete provenance");
  phase="replay";const replay=await service.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,statement));assert(!replay.error&&replay.data.idempotent&&Object.keys(result).filter(k=>k!=="idempotent").every(k=>(replay.data as Record<string,unknown>)[k]===(result as unknown as Record<string,unknown>)[k]),"same IDs replay");assert((await service.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,request,"changed"))).error?.code==="23505","changed payload conflict");const changedKey=await service.rpc("zeya_promote_voice_candidate_to_canonical",args(owner,c,crypto.randomUUID(),statement));assert(!changedKey.error&&changedKey.data.idempotent&&changedKey.data.canonicalizationId===result.canonicalizationId,"changed key converges for the same material payload");
  phase="immutability";assert(!(await owner.user.client.from("conversation_candidate_canonicalizations").select("id").eq("id",result.canonicalizationId)).error,"owner SELECT");assert((await foreign.user.client.from("conversation_candidate_canonicalizations").select("id").eq("id",result.canonicalizationId)).data?.length===0,"foreign SELECT isolated");for(const client of [owner.user.client,anon,service]){assert((await client.from("conversation_candidate_canonicalizations").insert({id:crypto.randomUUID()})).error,"direct insert blocked");assert((await client.from("conversation_candidate_canonicalizations").update({request_hash:"x"}).eq("id",result.canonicalizationId)).error,"update blocked");assert((await client.from("conversation_candidate_canonicalizations").delete().eq("id",result.canonicalizationId)).error,"delete blocked")}
  phase="stale baseline";const staleTenant=await tenant("stale"),stale=await candidate(staleTenant,"stale"),advanceEvidence=await jsonRequest<any>(server.baseUrl,"/api/representation/evidence",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${staleTenant.user.token}`},body:JSON.stringify({businessId:staleTenant.businessId,statement:"advance baseline"})});assert(advanceEvidence.status===201,"stale advance proposal");registry.registerEvidence(advanceEvidence.body.data.evidenceId);registry.registerObservation(advanceEvidence.body.data.observationId);registry.registerProposal(advanceEvidence.body.data.proposalId);const advance=await jsonRequest<any>(server.baseUrl,"/api/representation/versions",{method:"POST",headers:{"content-type":"application/json",Authorization:`Bearer ${staleTenant.user.token}`},body:JSON.stringify({businessRepresentationId:staleTenant.representationId,proposalId:advanceEvidence.body.data.proposalId,elementValues:{voice_target:{value:"advanced"}},confidenceScore:75})});assert(advance.status===201,"stale advance Version");registry.registerVersion(advance.body.data.versionId);registry.registerConfidenceAssessment(advance.body.data.confidenceAssessmentId);const staleCall=await service.rpc("zeya_promote_voice_candidate_to_canonical",args(staleTenant,stale,crypto.randomUUID(),"stale attempt"));assert(staleCall.error?.message==="canonical baseline changed",`exact stale rejection: ${JSON.stringify(staleCall.error)}`);assert((await service.from("conversation_candidate_promotions").select("id").eq("candidate_id",stale.id)).data?.length===0,"stale has no promotion");
  phase="rollback";const rollbackTenant=await tenant("rollback"),rollbackCandidate=await candidate(rollbackTenant,"rollback"),beforeQuery=await service.from("business_representations").select("current_version_id").eq("id",rollbackTenant.representationId).single();if(beforeQuery.error)throw beforeQuery.error;const before=beforeQuery.data.current_version_id;sql("ALTER TABLE public.confidence_assessments ADD CONSTRAINT zeya_test_reject_voice_canonicalization CHECK (calculation_method <> 'voice_candidate_canonicalization_v1') NOT VALID");rollbackConstraint=true;const failed=await service.rpc("zeya_promote_voice_candidate_to_canonical",args(rollbackTenant,rollbackCandidate,crypto.randomUUID(),"rollback proof"));assert(failed.error?.code==="23514","forced downstream constraint failure");sql("ALTER TABLE public.confidence_assessments DROP CONSTRAINT zeya_test_reject_voice_canonicalization");rollbackConstraint=false;for(const table of ["conversation_candidate_review_decisions","conversation_candidate_promotions","conversation_candidate_canonicalizations"]){assert((await service.from(table).select("id").eq("candidate_id",rollbackCandidate.id)).data?.length===0,`${table} rolled back`)}const afterQuery=await service.from("business_representations").select("current_version_id").eq("id",rollbackTenant.representationId).single();if(afterQuery.error)throw afterQuery.error;assert(afterQuery.data.current_version_id===before,"pointer rolled back");assert((await service.from("representation_versions").select("id").eq("business_representation_id",rollbackTenant.representationId)).data?.length===1,"Version rolled back");
  phase="concurrency";const concurrentTenant=await tenant("concurrent"),concurrentCandidate=await candidate(concurrentTenant,"concurrent"),concurrentArgs=args(concurrentTenant,concurrentCandidate,crypto.randomUUID(),"concurrent proof"),settled=await Promise.allSettled([service.rpc("zeya_promote_voice_candidate_to_canonical",concurrentArgs),service.rpc("zeya_promote_voice_candidate_to_canonical",concurrentArgs)]),responses=settled.filter(x=>x.status==="fulfilled").map(x=>(x as PromiseFulfilledResult<any>).value);assert(responses.length===2&&responses.every(x=>!x.error),"concurrent calls succeed");assert(responses[0].data.canonicalizationId===responses[1].data.canonicalizationId&&responses.some(x=>x.data.idempotent),"concurrency converges");track(concurrentTenant,responses[0].data);for(const [table,column] of [["conversation_candidate_canonicalizations","candidate_id"],["conversation_candidate_promotions","candidate_id"]] as const)assert((await service.from(table).select("id").eq(column,concurrentCandidate.id)).data?.length===1,`${table} single row`);
  console.log("Voice candidate atomic canonicalization deployed — PASS");
 }catch(error){throw new Error(`${phase}: ${error instanceof Error?error.message:JSON.stringify(error)}`)}finally{if(rollbackConstraint){try{sql("ALTER TABLE public.confidence_assessments DROP CONSTRAINT IF EXISTS zeya_test_reject_voice_canonicalization")}catch{}}cleanup=await cleanupFixtures(service,registry);await server.stop();console.log(`Canonicalization cleanup — ${cleanup.success?"PASS":"FAIL"}`)}if(!cleanup?.success)throw new Error(cleanup?.failures.join(", "));
}
main().catch(e=>{console.error(e);process.exit(1)});
