-- Phase 5A post-deployment verification. Read-only. Every row must return passed = true.
WITH policy_inventory AS (
  SELECT n.nspname AS schema_name, c.relname AS table_name, p.polname AS policy_name,
    p.polcmd AS command,
    COALESCE((SELECT array_agg(CASE WHEN role_oid=0 THEN 'public' ELSE pg_catalog.pg_get_userbyid(role_oid) END ORDER BY role_oid) FROM unnest(p.polroles) role_oid),'{}'::name[]) AS roles,
    pg_catalog.pg_get_expr(p.polqual,p.polrelid) AS using_expression
  FROM pg_catalog.pg_policy p JOIN pg_catalog.pg_class c ON c.oid=p.polrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace
  WHERE n.nspname='public'
), checks(check_name, passed, details) AS (
  SELECT 'provenance_columns_exact', count(*)=10, jsonb_build_object('actual_count',count(*),'expected_count',10)
  FROM (SELECT c.relname,a.attname FROM pg_catalog.pg_attribute a JOIN pg_catalog.pg_class c ON c.oid=a.attrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND NOT a.attisdropped AND (c.relname,a.attname) IN (('evidence','source_public_experience_session_id'),('evidence','source_voice_conversation_output_id'),('evidence','source_voice_context_id'),('evidence','source_tenant_user_id'),('evidence','source_business_id'),('evidence','source_canonical_version_id'),('evidence','source_mission_id'),('evidence','source_provider_conversation_id'),('evidence','source_provider_call_id'),('voice_conversation_candidates','source_evidence_id'))) columns
  UNION ALL
  SELECT 'governed_learning_constraints_present', count(*)=4, jsonb_build_object('actual_count',count(*),'expected_count',4)
  FROM pg_catalog.pg_constraint c JOIN pg_catalog.pg_namespace n ON n.oid=c.connamespace WHERE n.nspname='public' AND c.conname IN ('evidence_interaction_provenance_complete','evidence_interaction_output_identity_fk','evidence_interaction_session_identity_fk','voice_candidate_source_evidence_identity_fk')
  UNION ALL
  SELECT 'governed_learning_indexes_present', count(*)=4, jsonb_build_object('actual_count',count(*),'expected_count',4)
  FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='i' AND c.relname IN ('voice_outputs_governed_learning_identity_idx','public_experience_governed_learning_identity_idx','evidence_interaction_output_unique_idx','evidence_governed_learning_identity_idx')
  UNION ALL
  SELECT 'interaction_evidence_authority_trigger', count(*)=1 AND bool_and(NOT t.tgisinternal) AND bool_and(t.tgenabled='O'), jsonb_build_object('actual_count',count(*),'enabled',COALESCE(bool_and(t.tgenabled='O'),false))
  FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_class c ON c.oid=t.tgrelid JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname='evidence' AND t.tgname='zeya_interaction_evidence_authority'
  UNION ALL
  SELECT 'interaction_evidence_authority_function', count(*)=1 AND bool_and(pg_catalog.pg_get_userbyid(p.proowner)='postgres') AND bool_and(NOT p.prosecdef) AND bool_and(p.prokind='f') AND bool_and(pg_catalog.format_type(p.prorettype,NULL)='trigger') AND bool_and(p.provolatile='v') AND bool_and(p.proconfig=ARRAY['search_path=""']::text[]) AND bool_and(pg_catalog.has_function_privilege('postgres',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('public',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('anon',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('authenticated',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('service_role',p.oid,'EXECUTE')) AND bool_and(pg_catalog.regexp_replace(p.prosrc,'[[:space:]]+','','g') LIKE '%current_user<>''postgres''%') AND bool_and(pg_catalog.regexp_replace(p.prosrc,'[[:space:]]+','','g') LIKE '%current_setting(''zeya.governed_learning_write'',true)<>''on''%') AND bool_and(p.prosrc LIKE '%interaction Evidence creation is not authorized%'),
    jsonb_build_object('exact_signature',COALESCE(min(p.oid::regprocedure::text),'<missing>'),'owner',COALESCE(min(pg_catalog.pg_get_userbyid(p.proowner)),'<missing>'),'security_definer',COALESCE(bool_and(p.prosecdef),false),'configuration',COALESCE(min(p.proconfig::text),'<missing>'),'return_type',COALESCE(min(pg_catalog.format_type(p.prorettype,NULL)),'<missing>'),'acl',COALESCE(min(p.proacl::text),'<missing>'),'postgres_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('postgres',p.oid,'EXECUTE')),false),'public_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('public',p.oid,'EXECUTE')),false),'anon_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('anon',p.oid,'EXECUTE')),false),'authenticated_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('authenticated',p.oid,'EXECUTE')),false),'service_role_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('service_role',p.oid,'EXECUTE')),false),'current_user_guard',COALESCE(bool_and(pg_catalog.regexp_replace(p.prosrc,'[[:space:]]+','','g') LIKE '%current_user<>''postgres''%'),false),'transaction_local_setting',COALESCE(bool_and(pg_catalog.regexp_replace(p.prosrc,'[[:space:]]+','','g') LIKE '%current_setting(''zeya.governed_learning_write'',true)<>''on''%'),false),'authorization_error',COALESCE(bool_and(p.prosrc LIKE '%interaction Evidence creation is not authorized%'),false),'definition_md5',COALESCE(min(md5(pg_catalog.pg_get_functiondef(p.oid))),'<missing>'))
  FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.oid=pg_catalog.to_regprocedure('public.zeya_enforce_interaction_evidence_authority()')
  UNION ALL
  SELECT 'candidate_store_rpc_secure_and_exact', count(*)=1 AND bool_and(pg_catalog.pg_get_userbyid(p.proowner)='postgres') AND bool_and(p.prosecdef) AND bool_and(p.prokind='f') AND bool_and(pg_catalog.format_type(p.prorettype,NULL)='integer') AND bool_and(p.provolatile='v') AND bool_and(p.proconfig=ARRAY['search_path=""']::text[]) AND bool_and(pg_catalog.has_function_privilege('service_role',p.oid,'EXECUTE')) AND bool_and(pg_catalog.has_function_privilege('postgres',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('public',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('anon',p.oid,'EXECUTE')) AND bool_and(NOT pg_catalog.has_function_privilege('authenticated',p.oid,'EXECUTE')),
    jsonb_build_object('exact_signature',COALESCE(min(p.oid::regprocedure::text),'<missing>'),'exact_signature_count',count(*),'named_overload_count',(SELECT count(*) FROM pg_catalog.pg_proc q JOIN pg_catalog.pg_namespace qn ON qn.oid=q.pronamespace WHERE qn.nspname='public' AND q.proname='zeya_store_voice_conversation_candidates'),'owner',COALESCE(min(pg_catalog.pg_get_userbyid(p.proowner)),'<missing>'),'security_definer',COALESCE(bool_and(p.prosecdef),false),'configuration',COALESCE(min(p.proconfig::text),'<missing>'),'return_type',COALESCE(min(pg_catalog.format_type(p.prorettype,NULL)),'<missing>'),'volatility',COALESCE(min(p.provolatile),'<missing>'),'execute_grantees',COALESCE((SELECT jsonb_agg(grantee ORDER BY grantee) FROM (SELECT DISTINCT CASE WHEN x.grantee=0 THEN 'public' ELSE pg_catalog.pg_get_userbyid(x.grantee) END AS grantee FROM pg_catalog.pg_proc ap CROSS JOIN LATERAL aclexplode(COALESCE(ap.proacl,pg_catalog.acldefault('f',ap.proowner))) x WHERE ap.oid=pg_catalog.to_regprocedure('public.zeya_store_voice_conversation_candidates(uuid,text,jsonb)') AND x.privilege_type='EXECUTE') g),'[]'::jsonb),'public_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('public',p.oid,'EXECUTE')),false),'anon_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('anon',p.oid,'EXECUTE')),false),'authenticated_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('authenticated',p.oid,'EXECUTE')),false),'postgres_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('postgres',p.oid,'EXECUTE')),false),'service_role_execute',COALESCE(bool_and(pg_catalog.has_function_privilege('service_role',p.oid,'EXECUTE')),false),'definition_md5',COALESCE(min(md5(pg_catalog.pg_get_functiondef(p.oid))),'<missing>'))
  FROM pg_catalog.pg_proc p JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.oid=pg_catalog.to_regprocedure('public.zeya_store_voice_conversation_candidates(uuid,text,jsonb)')
  UNION ALL
  SELECT 'candidate_store_rpc_governed_learning_semantics', count(*)=1 AND bool_and(s.src LIKE '%source_public_experience_session_id%') AND bool_and(s.src LIKE '%source_voice_conversation_output_id%') AND bool_and(s.src LIKE '%source_canonical_version_id%') AND bool_and(s.src LIKE '%source_evidence_id%') AND bool_and(s.src LIKE '%public_experience_governed_learning%') AND bool_and(s.src LIKE '%candidatereferencesunauthorizedRepresentationElement%') AND bool_and(s.src LIKE '%set_config(''zeya.governed_learning_write'',''on'',true)%') AND bool_and(s.src LIKE '%publicexperiencegoverned-learninglineagemismatch%') AND bool_and(s.src NOT LIKE '%insertintopublic.representation_versions%') AND bool_and(s.src NOT LIKE '%updatepublic.business_representations%') AND bool_and(s.src NOT LIKE '%updatepublic.representation_elements%') AND bool_and(s.src NOT LIKE '%insertintopublic.approval_decisions%'),
    jsonb_build_object('definition_md5',COALESCE(min(md5(pg_catalog.pg_get_functiondef(s.oid))),'<missing>'),'source_public_experience_session_id',COALESCE(bool_and(s.src LIKE '%source_public_experience_session_id%'),false),'source_voice_conversation_output_id',COALESCE(bool_and(s.src LIKE '%source_voice_conversation_output_id%'),false),'source_canonical_version_id',COALESCE(bool_and(s.src LIKE '%source_canonical_version_id%'),false),'source_evidence_id',COALESCE(bool_and(s.src LIKE '%source_evidence_id%'),false),'governed_learning_audit',COALESCE(bool_and(s.src LIKE '%public_experience_governed_learning%'),false),'authorized_element_keys',COALESCE(bool_and(s.src LIKE '%candidatereferencesunauthorizedRepresentationElement%'),false),'transaction_local_write',COALESCE(bool_and(s.src LIKE '%set_config(''zeya.governed_learning_write'',''on'',true)%'),false),'lineage_mismatch',COALESCE(bool_and(s.src LIKE '%publicexperiencegoverned-learninglineagemismatch%'),false),'canonical_versions_insert_absent',COALESCE(bool_and(s.src NOT LIKE '%insertintopublic.representation_versions%'),false),'canonical_pointer_update_absent',COALESCE(bool_and(s.src NOT LIKE '%updatepublic.business_representations%'),false),'element_pointer_update_absent',COALESCE(bool_and(s.src NOT LIKE '%updatepublic.representation_elements%'),false),'approval_insert_absent',COALESCE(bool_and(s.src NOT LIKE '%insertintopublic.approval_decisions%'),false))
  FROM (SELECT p.*,pg_catalog.regexp_replace(p.prosrc,'[[:space:]]+','','g') AS src FROM pg_catalog.pg_proc p WHERE p.oid=pg_catalog.to_regprocedure('public.zeya_store_voice_conversation_candidates(uuid,text,jsonb)')) s
  UNION ALL
  SELECT 'tenant_select_policies_preserved',
    (SELECT EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='evidence' AND p.policy_name='evidence_select' AND p.command='r' AND 'public'=ANY(p.roles) AND p.using_expression ILIKE '%business_representations%' AND p.using_expression ILIKE '%auth.uid()%')) AND
    (SELECT EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='representation_proposals' AND p.policy_name='representation_proposals_select' AND p.command='r' AND 'public'=ANY(p.roles) AND p.using_expression ILIKE '%business_representations%' AND p.using_expression ILIKE '%auth.uid()%')) AND
    (SELECT EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='voice_conversation_outputs' AND p.policy_name='voice_outputs_tenant_select' AND p.command='r' AND 'authenticated'=ANY(p.roles) AND p.using_expression ILIKE '%tenant_user_id%' AND p.using_expression ILIKE '%auth.uid()%')) AND
    (SELECT EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='voice_conversation_candidates' AND p.policy_name='voice_candidates_tenant_select' AND p.command='r' AND 'authenticated'=ANY(p.roles) AND p.using_expression ILIKE '%tenant_user_id%' AND p.using_expression ILIKE '%auth.uid()%')),
    jsonb_build_object('evidence_select',EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='evidence' AND p.policy_name='evidence_select' AND p.command='r' AND 'public'=ANY(p.roles) AND p.using_expression ILIKE '%business_representations%' AND p.using_expression ILIKE '%auth.uid()%'),'representation_proposals_select',EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='representation_proposals' AND p.policy_name='representation_proposals_select' AND p.command='r' AND 'public'=ANY(p.roles) AND p.using_expression ILIKE '%business_representations%' AND p.using_expression ILIKE '%auth.uid()%'),'voice_outputs_tenant_select',EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='voice_conversation_outputs' AND p.policy_name='voice_outputs_tenant_select' AND p.command='r' AND 'authenticated'=ANY(p.roles) AND p.using_expression ILIKE '%tenant_user_id%' AND p.using_expression ILIKE '%auth.uid()%'),'voice_candidates_tenant_select',EXISTS (SELECT 1 FROM policy_inventory p WHERE p.table_name='voice_conversation_candidates' AND p.policy_name='voice_candidates_tenant_select' AND p.command='r' AND 'authenticated'=ANY(p.roles) AND p.using_expression ILIKE '%tenant_user_id%' AND p.using_expression ILIKE '%auth.uid()%'))
  UNION ALL
  SELECT 'canonical_state_untouched_by_migration', NOT EXISTS (SELECT 1 FROM pg_catalog.pg_proc p WHERE p.oid=pg_catalog.to_regprocedure('public.zeya_store_voice_conversation_candidates(uuid,text,jsonb)') AND (p.prosrc LIKE '%INSERT INTO public.representation_versions%' OR p.prosrc LIKE '%UPDATE public.business_representations%' OR p.prosrc LIKE '%UPDATE public.representation_elements%' OR p.prosrc LIKE '%INSERT INTO public.approval_decisions%')), jsonb_build_object('canonical_mutation_statements_present',false)
)
SELECT check_name, passed, details
FROM checks
ORDER BY check_name;
